#!/bin/bash
# Deploy to Vercel
# Run: vercel --prod
# Set environment variables in Vercel dashboard or via .env.local

vercel --prod \
  -e MIDTRANS_SERVER_KEY="$MIDTRANS_SERVER_KEY" \
  -e NEXT_PUBLIC_MIDTRANS_CLIENT_KEY="$NEXT_PUBLIC_MIDTRANS_CLIENT_KEY" \
  -e NEXT_PUBLIC_MIDTRANS_IS_PRODUCTION="${NEXT_PUBLIC_MIDTRANS_IS_PRODUCTION:-false}" \
  -e NEXT_PUBLIC_PHOTO_PRICE="${NEXT_PUBLIC_PHOTO_PRICE:-15000}" \
  -e VOUCHER_CODES="$VOUCHER_CODES" \
  -e NEXT_PUBLIC_PRINT_PRICE="${NEXT_PUBLIC_PRINT_PRICE:-5000}" \
  -e NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME="$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME" \
  -e NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET="$NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET"
